apiVersion: v1
kind: Service
metadata:
  labels:
    app: config-server
  name: config-server
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: http
    nodePort: 32088
  selector:
    app: config-server
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  labels:
    app: config-server
  name: config-server
spec:
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
      - env:
        #- name: KUBERNETES_TRUST_CERTIFICATES
        #  value: "true"
        #- name: SPRING_CLOUD_KUBERNETES_CONFIG_NAMESPACE
        #  valueFrom:
        #      fieldRef:
        #        fieldPath: metadata.namespace
        image: kingbike/config-server:latest
        imagePullPolicy: Always 
        name: config-server
        ports:
          - name: http
            containerPort: 8888
          #- name: actuator
          #  containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 500m
            memory: 256Mi
        #livenessProbe:
        #  httpGet:
        #    path: /actuator/health
        #    port: actuator
        #  initialDelaySeconds: 60
        #readinessProbe:
        #  httpGet:
        #    path: /actuator/health
        #    port: actuator
